# Generated by Django 5.2.3 on 2025-06-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('MACHINE', 'Machine'), ('MOLD', 'Mold'), ('EQUIPMENT', 'Equipment'), ('FURNITURE', 'Furniture'), ('VEHICLE', 'Vehicle'), ('BUILDING', 'Building'), ('TECHNOLOGY', 'Technology'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
