# Generated by Django 5.2.3 on 2025-12-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('SALES', 'Sales Report'), ('INVENTORY', 'Inventory Report'), ('CUSTOMER', 'Customer Report'), ('VENDOR', 'Vendor Report'), ('FINANCIAL', 'Financial Report')], max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('parameters', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
