# Generated by Django 5.2.3 on 2025-11-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawmaterial',
            unique_together={('name', 'unit')},
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='supplier_contact',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='unit_price',
        ),
    ]
