# Generated by Django 5.2.3 on 2025-12-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Original initial migration — only created the base Product table.
    SizeRange, Color, ProductVariant were added in 0002_add_productvariant.
    """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[
                    ('BAG', 'Bag'), ('KILO', 'Kilo'), ('PCS', 'Pieces'), ('KG', 'Kilograms'),
                    ('L', 'Liters'), ('M', 'Meters'), ('BOX', 'Box'), ('PACK', 'Pack'),
                    ('UNIT', 'Unit'), ('GRAM', 'Grams'), ('TON', 'Tons'), ('GALLON', 'Gallons'),
                    ('FOOT', 'Feet'), ('YARD', 'Yards'), ('CM', 'Centimeters'), ('MM', 'Millimeters'),
                    ('INCH', 'Inches'), ('POUND', 'Pounds'), ('OUNCE', 'Ounces'), ('CUP', 'Cups'),
                    ('TABLESPOON', 'Tablespoons'), ('TEASPOON', 'Teaspoons'),
                ], max_length=20)),
                ('cop', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
