# Generated by Django 5.2.3 on 2026-08-08 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_sizerange_color_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('MANUFACTURED', 'Manufactured Product'), ('PURCHASED', 'Purchased Item')], default='MANUFACTURED', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.sizerange'),
        ),
    ]
