# Generated by Django 5.2.3 on 2025-11-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20251115_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('MANUFACTURED', 'Manufactured Product'), ('PURCHASED', 'Purchased Item')], default='MANUFACTURED', max_length=20),
        ),
    ]
