# Generated by Django 5.2.3 on 2025-12-21 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0003_sizerange_color_productvariant'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.color'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='size_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.sizerange'),
        ),
    ]
