# Generated by Django 5.2.3 on 2026-08-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_billno_saletype_saleitem_dozens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='bill_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=10),
        ),
    ]
