# Generated by Django 5.2.3 on 2025-11-14 20:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20251115_0026'),
        ('raw_materials', '0002_alter_rawmaterial_unique_together_and_more'),
        ('vendors', '0002_rename_city_vendor_contact_person_vendor_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('PRODUCT', 'Finished Product'), ('RAW_MATERIAL', 'Raw Material')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_order_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('lead_time_days', models.IntegerField(default=0, help_text='Lead time in days')),
                ('is_preferred', models.BooleanField(default=False, help_text='Mark as preferred supplier for this item')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('last_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_supplies', to='products.product')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_supplies', to='raw_materials.rawmaterial')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='vendors.vendor')),
            ],
            options={
                'ordering': ['vendor__name', 'product_type'],
                'constraints': [models.CheckConstraint(condition=models.Q(('product__isnull', False), ('raw_material__isnull', False), _connector='OR'), name='vendor_product_item_required'), models.CheckConstraint(condition=models.Q(('product__isnull', False), ('raw_material__isnull', False), _negated=True), name='vendor_product_only_one_item')],
            },
        ),
    ]
