# Generated by Django 5.2.3 on 2026-08-08 23:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_product_product_type_alter_product_size_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_dozen', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('valid_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_costs', to='profit.costcomponenttype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='products.product')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
    ]
